#lang info

;; Package metadata.
(define version "1.0")
(define deps '("base"))

;; Define colors
(define black        #(30 30 30))
(define dark-gray    #(40 43 46))
(define med-gray     #(70 70 70))
(define light-gray   #(133 133 133))
(define white        #(212 212 212))
(define pink         #(197 134 192))
(define dark-blue    #(79 193 255))
(define light-blue   #(156 220 254))
(define dark-green   #(78 201 176))
(define med-green    #(177 201 164))
(define light-green  #(106 153 85))
(define orange       #(206 145 120))
(define yellow       #(220 220 170))
(define light-red    #(117 0 0))
(define red          #(244 71 71))

(define framework:color-schemes
  `(#hash((name . "VSCode Dark")
          (white-on-black-base? . #t)
          (colors
           .
           ((drracket:error-background-highlighting                       ,light-red)
            (drracket:language-name-and-memory-use-at-top-of-interactions ,light-green)
            (drracket:syncheck:matching-identifiers                       ,dark-gray)
            (framework:basic-canvas-background                            ,black)
            (framework:default-text-color                                 ,white)
            (framework:line-numbers                                       ,light-gray)
            (framework:line-numbers-current-line-number-background        ,black)
            (framework:line-numbers-current-line-number-foreground        ,black)
            (framework:line-numbers-when-word-wrapping                    ,black)
            (framework:misspelled-text-color                              ,white)
            (framework:paren-match-color                                  ,med-gray)
            (framework:program-contour-current-location-bar               ,light-gray)
            (framework:warning-background-color                           ,red)
            (drracket:check-syntax:both-obligation-style-pref             ,light-gray)
            (drracket:check-syntax:free-variable                          ,red)
            (drracket:check-syntax:imported                               ,pink)
            (drracket:check-syntax:lexically-bound                        ,light-blue)
            (drracket:check-syntax:my-obligation-style-pref               ,red)
            (drracket:check-syntax:set!d                                  ,red)
            (drracket:check-syntax:their-obligation-style-pref            ,light-green)
            (drracket:check-syntax:unk-obligation-style-pref              ,white)
            (drracket:check-syntax:unused-require                         ,red)
            (drracket:read-eval-print-loop:error-color                    ,red)
            (drracket:read-eval-print-loop:out-color                      ,light-blue)
            (drracket:read-eval-print-loop:value-color                    ,med-green)
            (framework:syntax-color:scheme:comment                        ,light-green)
            (framework:syntax-color:scheme:constant                       ,med-green)
            (framework:syntax-color:scheme:error                          ,red)
            (framework:syntax-color:scheme:hash-colon-keyword             ,light-green)
            (framework:syntax-color:scheme:keyword                        ,pink)
            (framework:syntax-color:scheme:other                          ,white)
            (framework:syntax-color:scheme:parenthesis                    ,white)
            (framework:syntax-color:scheme:string                         ,orange)
            (framework:syntax-color:scheme:symbol                         ,light-blue)
            (framework:syntax-color:scheme:text                           ,orange)
            (plt:htdp:test-coverage-off                                   ,red)
            (plt:htdp:test-coverage-on                                    ,white)
            (plt:module-language:test-coverage-off                        ,red)
            (plt:module-language:test-coverage-on                         ,white))))))
